// Copyright © 2025-2026 Oleksandr Kukhtin. All rights reserved.

using System;

namespace A2v10.Metadata;

internal static class Constants
{
    public const Int32 MultilineThreshold = 200;

    public static class FieldNames
    {
        public const String Id = nameof(Id);
        public const String Name = nameof(Name);
        public const String Memo = nameof(Memo);
        public const String Void = nameof(Void);
        public const String IsSystem = nameof(IsSystem);
        public const String RowNo = nameof(RowNo);
        public const String Date = nameof(Date);
        public const String Done = nameof(Done);
        public const String Document = nameof(Document);
        public const String RowVersion = "rv";
        public const String Parent = nameof(Parent);
        // 'Parent' in the model: the word is reserved there - see TableColumn.ModelName
        public const String ParentElem = nameof(ParentElem);
        public const String Folder = nameof(Folder);
        public const String Color = nameof(Color);
        public const String For = nameof(For);
        public const String Tag = nameof(Tag);
        public const String Tags = nameof(Tags);
        public const String Order = nameof(Order);
        public const String Pattern = nameof(Pattern);
        public const String Period = nameof(Period);
        // the counters table: which numbering, which period, where it has got to
        public const String Autonum = nameof(Autonum);
        public const String Year = nameof(Year);
        public const String Quart = nameof(Quart);
        public const String Month = nameof(Month);
        public const String CurrentNumber = nameof(CurrentNumber);
        // a chart of accounts
        public const String AccountType = nameof(AccountType);
        public const String NormalBalance = nameof(NormalBalance);
        // a set of states: what the value is to the cycle - see StateRole
        public const String Role = nameof(Role);
        // a ledger: the leg's sign, its account, the account it corresponds to, its sum
        public const String InOut = nameof(InOut);
        public const String Acc = nameof(Acc);
        public const String CorrAcc = nameof(CorrAcc);
        public const String Sum = nameof(Sum);
        // the children of a tree node: the SQL declares it ('!Items'), the TreeGrid walks it
        public const String Items = nameof(Items);
        // stamps: who + when, see ColumnType.StampUser
        public const String UserCreated = nameof(UserCreated);
        public const String UtcDateCreated = nameof(UtcDateCreated);
        public const String UserModified = nameof(UserModified);
        public const String UtcDateModified = nameof(UtcDateModified);
        public const String UserPosted = nameof(UserPosted);
        public const String UtcDatePosted = nameof(UtcDatePosted);
    }
    public static class FieldSizes
    {
        public const Int32 Name = 255;
        public const Int32 Memo = 255;
    }

    public static class FormNames
    {
        public const String Index  = "index";
        public const String Edit   = "edit";
        public const String Open   = "open";
        public const String Show   = "show";
        public const String Browse = "browse";
    }

    /* The shell of the transactions dialog - an object with no data of its own, carrying which tab
     * is in front. Here because the SQL writes these names and the XAML binds to them, and the two
     * are generated by different builders (SqlBuilderTrans, TransDialogXaml).
     */
    public static class Trans
    {
        public const String Action = "showtrans";
        public const String Root = nameof(Trans);
        public const String TypeName = "TTrans";
        public const String Tab = nameof(Tab);
    }

    /* A print blank is reached by an action of the endpoint, with the blank named in the query -
     * 'document/waybillin/print/2222?Form=printform1'. Two segments and an id, like every other
     * action; WHICH blank cannot ride in the path, because ParsePath takes no third segment.
     */
    public static class Print
    {
        public const String Action = "print";
        public const String FormQuery = "Form";
    }

    public static class SqlNames
    {
        /* A list of ids and nothing else, on the real 'platformid' - which is why it is ours and
         * not a2sys.[Id.TableType]: that one is declared 'bigint', and a database whose platformid
         * is uniqueidentifier would take the rows and write none. Lives beside 'platformid' itself.
         */
        public const String IdTableType = "dbo.[PlatformId.TableType]";
    }

    /* Platform entries of the filter namespace - the ones a trait or the kind contributes, as
     * opposed to the ones a column contributes under its own name. See FilterMetadata.
     */
    public static class FilterNames
    {
        public const String Period = nameof(Period);
        public const String Tags = nameof(Tags);
    }

    public static class SchemaNames
    {
        public const String Catalog = "catalog";
        public const String Document = "document";
        public const String Journal = "journal";
        public const String Details = "details";
        public const String Report = "report";
        /* Platform-owned namespaces: their endpoints are declared in code, not in files. Own
         * namespaces on purpose - inside catalog/ or document/ they would be shadowed by, or
         * confused with, an application endpoint of the same name.
         */
        public const String Operation = "operation";
        public const String Tag = "tag";
        /* One step further than those two: an enum has no endpoint at all, in code or in files.
         * The namespace exists so that a reference can name a set by address.
         */
        public const String Enum = "enum";
        /* The second kind of set: its values carry a colour and a role in a life cycle, so a
         * reference to one says the record HAS a life cycle. Named after the entity whose states
         * they are - /state/order - which is why the model is composed and not the folder alone
         * (TableMetadata.SetDefaults): the candidates ride in the root of that entity's own page,
         * where 'Order' is already taken by the entity itself.
         */
        public const String State = "state";
        /* One file at the root and no folders under it: there is one registry of numberings, and
         * its schema, table and model default in TableMetadata.SetDefaults. The price is locality -
         * what 'waybill' is cannot be read beside the endpoint that names it, and the file grows
         * with the application. What makes that affordable is that the name resolves at load, so a
         * wrong one fails there and not at the first save.
         */
        public const String Autonum = "autonum";
        /* A chart of accounts, always named - /accplan/national - even when there is one: a bare
         * accplan/metadata.json would be a second spelling of the same fact, and a second plan would
         * move the first one together with every reference to it.
         */
        public const String AccPlan = "accplan";
        // the postings against one chart of accounts - two mirrored legs per posting
        public const String Ledger = "ledger";
    }

    /* Folders of a module's own layout: first segments with no endpoints of their own, so not a
     * namespace and not in SchemaNames. Reserved beside them all the same - an alias of that name
     * would make a path read two ways.
     */
    public static class ModuleFolders
    {
        // $crm/patches/catalog/agent - what follows is the address of the node patched, not a node of the module
        public const String Patches = "patches";
    }
}
