// Copyright © 2026 Oleksandr Kukhtin. All rights reserved.

using System;
using System.IO;
using System.Threading.Tasks;

using Microsoft.Data.SqlClient;
using Microsoft.Extensions.DependencyInjection;

using A2v10.Data.Interfaces;

namespace A2v10.Metadata;

/* A test run over the application, from inside its host: the database the run owns, and the
 * scenarios. A service of the test host only - UseTestEnvironment, called by the harness, which
 * gives paths and nothing else.
 *
 * The database is the host's own 'Default', so what may be recreated is decided by its NAME: the
 * harness points 'Default' at TestConnectionString(the application's), which appends the suffix,
 * and CreateTestDatabaseAsync refuses a name without it. The suffix is written and read here alone,
 * so a run pointed at the application's data is not expressible - not merely unlikely.
 */
public sealed class TestEnvironment(IDbContext _dbContext, SqlDbGenerator _sqlDbGenerator, IServiceScopeFactory _scopeFactory)
{
    private const String Suffix = "_Test";

    public static String TestConnectionString(String appConnectionString)
    {
        var builder = new SqlConnectionStringBuilder(appConnectionString);
        if (String.IsNullOrEmpty(builder.InitialCatalog))
            throw new InvalidOperationException("The connection string names no database, and the test database is named after it.");
        builder.InitialCatalog += Suffix;
        return builder.ConnectionString;
    }

    /* Recreated at the start of a run and never dropped: after a failure the state is still there
     * to open the application on. Empty, then full.sql - the platform, deploydatabase.sql and app.sql
     * as the build of the host left them - executed as 'a2 meta deploy --full' executes it. The
     * metadata is the caller's to deploy after: deploydatabase.sql on disk may be older than it.
     */
    public async Task CreateTestDatabaseAsync(String fullSqlPath)
    {
        if (!File.Exists(fullSqlPath))
            throw new InvalidOperationException($"'{fullSqlPath}' not found. It is generated by the build of the host.");

        var connectionString = _dbContext.ConnectionString(null)
            ?? throw new InvalidOperationException("The host has no default connection string.");
        var name = new SqlConnectionStringBuilder(connectionString).InitialCatalog;
        if (!name.EndsWith(Suffix, StringComparison.Ordinal))
            throw new InvalidOperationException($"'{name}' is not a test database: the host's 'Default' must come from TestEnvironment.TestConnectionString.");

        var master = new SqlConnectionStringBuilder(connectionString) { InitialCatalog = "master" }.ConnectionString;
        using (var cnn = new SqlConnection(master))
        {
            await cnn.OpenAsync();
            using var cmd = new SqlCommand($"""
                if db_id({Literal(name)}) is not null
                begin
                    alter database {Identifier(name)} set single_user with rollback immediate;
                    drop database {Identifier(name)};
                end;
                create database {Identifier(name)};
                """, cnn);
            await cmd.ExecuteNonQueryAsync();
        }
        // a pooled connection to the database just dropped would be handed out first
        SqlConnection.ClearAllPools();

        await _sqlDbGenerator.DeployDatabaseAsync(null, fullSqlPath, await File.ReadAllTextAsync(fullSqlPath));
    }

    // every step in a scope of its own, as a request has
    public Task RunScenarioAsync(String file) => new ScenarioRunner(_scopeFactory).RunAsync(file);

    static String Identifier(String name) => $"[{name.Replace("]", "]]")}]";
    static String Literal(String name) => $"N'{name.Replace("'", "''")}'";
}
