<Project>
	<ItemGroup>
		<A2v10SchedulingSqlFiles Include="$(MSBuildThisFileDirectory)/../contentFiles/sql/*" />
	</ItemGroup>
	<Target Name="A2v10SchedulingCopySqlFiles" AfterTargets="Build">
		<Copy SourceFiles="@(A2v10SchedulingSqlFiles)" DestinationFolder="$(ProjectDir)/_assets/sql" SkipUnchangedFiles="true"/>
	</Target>
</Project>